# RUN: ansible-playbook cnf_node_speedtest.yaml  -i inventory.yaml -K
# run with -K to enter priv escalation password
---
- name: Client test machines setup
  hosts: ubuntu-01
  roles:
    - role: set_hostname
      vars:
        host_name: 
    - apt_upgrade
    - ssh_enabled
    - iperf3_service
  become: yes
  tasks:
    - name: install packages
      ansible.builtin.apt:
        pkg: 
          - xrdp
          - traceroute
          - curl
        state: present
        update_cache: yes

    - name: enable xrdp at boot
      ansible.builtin.systemd:
        name: xrdp.service
        enabled: yes
        state: restarted
        daemon_reload: yes

    - name: reset firewall
      community.general.ufw:
        state: reset